#!/bin/bash

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$BASH_SOURCE")" && pwd);

set -e

source "$SCRIPT_DIR/../../.env"

[ -z "${DEV_PREFIX}" ] && echo "DEV_PREFIX is undefined" && exit 1

[ ! -d "${DEV_PREFIX}" ] && mkdir -p "${DEV_PREFIX}"

sudo bash -s <<EEOM
echo "${DEV_PREFIX}" > /etc/ld.so.conf.d/shri314-resolver.conf
EEOM

(
   set -e
   rm -f gmp-6.1.2.tar.bz2
   wget http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.bz2
   tar xjf gmp-6.1.2.tar.bz2
   cd gmp-6.1.2
   ./configure --prefix=$DEV_PREFIX/gcc-deps/
   make -j10
   make install
)

sudo ldconfig

(
   set -e
   rm -f mpfr-3.1.5.tar.bz2
   wget http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.5.tar.bz2
   tar xjf mpfr-3.1.5.tar.bz2

   cd mpfr-3.1.5
   ./configure --prefix=$DEV_PREFIX/gcc-deps/ --with-gmp=$DEV_PREFIX/gcc-deps/
   make -j10
   make install
)

sudo ldconfig

(
   set -e
   rm -f mpc-1.0.3.tar.gz
   wget http://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
   tar xzf mpc-1.0.3.tar.gz

   cd mpc-1.0.3
   ./configure --prefix=$DEV_PREFIX/gcc-deps/ --with-gmp=$DEV_PREFIX/gcc-deps/ --with-mpfr=$DEV_PREFIX/gcc-deps/
   make -j10
   make install
)

sudo ldconfig

(
   set -e
   rm -f gcc-6.3.0.tar.bz2
   wget http://ftp.gnu.org/gnu/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2
   tar xjf gcc-6.3.0.tar.bz2

   rm -rf gcc-stage
   mkdir gcc-stage
   cd ./gcc-stage/
   ../gcc-6.3.0/configure --prefix=$DEV_PREFIX/gcc6 --with-gmp=$DEV_PREFIX/gcc-deps/ --with-mpfr=$DEV_PREFIX/gcc-deps/ --with-mpc=$DEV_PREFIX/gcc-deps/ \
       --enable-languages=c,c++ \
       --disable-bootstrap \
       --disable-multilib
   make -j10
   make install

   ( cd "$DEV_PREFIX" && rm -f gcc && ln -s gcc6 gcc )
)

sudo ldconfig
